# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        #skopeo copy docker://docker.elastic.co/elasticsearch/elasticsearch:8.1.0 docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/elasticsearch:8.1.0
        #skopeo copy docker://portainer/portainer:alpine docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/portainer:alpine
        #skopeo copy docker://portainer/portainer-ce docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/portainer:ce
        #skopeo copy docker://nginx:1.22.1-alpine docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/nginx:1.22.1-alpine
        #skopeo copy docker://mysql:5.7.22 docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/mysql:5.7.22
        skopeo copy docker://redis:latest docker://registry.cn-shenzhen.aliyuncs.com/cmmplb/redis:7.0-alpine